GET http://localhost:7070/milestones/list/1
Accept: application/json

###
POST http://localhost:7070/milestones/insert
Content-Type: application/json

{
  "projectSerialNumber": 1,
  "name": "공지"
}

###
PUT http://localhost:7070/milestones/update
Content-Type: application/json

{
  "serialNumber": 4,
  "name": "과제"
}

###
DELETE http://localhost:7070/milestones/delete/1

###

GET http://localhost:7070/tags/list/1
Accept: application/json

###
POST http://localhost:7070/tags/insert
Content-Type: application/json

{
  "projectSerialNumber": 1,
  "name": "springboot"
}

###
PUT http://localhost:7070/tags/update
Content-Type: application/json

{
  "serialNumber": 1,
  "name": "java"
}

###
DELETE http://localhost:7070/tags/delete/1

###
GET http://localhost:7070/projects/user
Accept: application/json

###
POST http://localhost:7070/projects/insert
Content-Type: application/json

{
  "adminId": "user",
  "name": "project1"
}