GET http://localhost:7070/milestones/list/1
Accept: application/json

###
POST http://localhost:7070/milestones/insert
Content-Type: application/json

{
  "projectSerialNumber": 2,
  "name": "마일스톤"
}

###
PUT http://localhost:7070/milestones/update
Content-Type: application/json

{
  "serialNumber": 4,
  "name": "과제"
}

###
DELETE http://localhost:7070/milestones/delete/1

###

GET http://localhost:7070/tags/list/1
Accept: application/json

###
POST http://localhost:7070/tags/insert
Content-Type: application/json

{
  "projectSerialNumber": 1,
  "name": "springboot"
}

###
PUT http://localhost:7070/tags/update
Content-Type: application/json

{
  "serialNumber": 1,
  "name": "java"
}

###
DELETE http://localhost:7070/tags/delete/1

###
GET http://localhost:7070/projects/user
Accept: application/json

###
POST http://localhost:7070/projects/insert
Content-Type: application/json

{
  "adminId": "user",
  "name": "project1"
}

###
GET http://localhost:7070/tasks/tags/2

###
GET http://localhost:7070/comments/3
Accept: application/json

###
GET http://localhost:7070/comments/list/2
Accept: application/json

###
POST http://localhost:7070/comments/insert
Content-Type: application/json

{
  "taskSerialNumber": 2,
  "memberId": "user",
  "projectSerialNumber": 1,
  "content": "댓글 생성"
}

###
PUT http://localhost:7070/comments/update
Content-Type: application/json

{
  "serialNumber": 4,
  "content": "댓글 수정"
}

###
DELETE http://localhost:7070/comments/delete/2

###
GET http://localhost:7070/tasks/list/1