###
GET http://localhost:7070/tags/1

###
GET http://localhost:7070/tags/list/1

###
POST http://localhost:7070/tags/insert
Content-Type: application/json

{
  "projectSerialNumber": 1,
  "name": "springboot"
}

###
PUT http://localhost:7070/tags/update
Content-Type: application/json

{
  "serialNumber": 1,
  "name": "java"
}

###
DELETE http://localhost:7070/tags/delete/1

