###
GET http://localhost:9090/members

###
POST http://localhost:9090/members/insert
Content-Type: application/json

{
  "id": "userTest",
  "password": "encryptedPassword",
  "email": "test@nhnacademy.com"
}

###
GET http://localhost:9090/members/userTest

###
GET http://localhost:9090/members/email/test@nhnacademy.com

###
GET http://localhost:9090/members/active/userTest

###
GET http://localhost:9090/members/dormant/userTest

###
GET http://localhost:9090/members/withdraw/userTest

